createTime: "2021-02-09T13:51:25.723862+11:00"
name: testapp
services:
  node-express:
    image: geshan/nodejs-docker-express
    port: 3000
    type: webservice
updateTime: "2021-02-09T13:51:25.723863+11:00"
